# Ejercicio: Extracción de datos de la API de TMDB (The Movie Database)

![imagen](https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg)

Trabajaremos con **TMDB**, una de las bases de datos de cine más importantes del mundo. El objetivo es extraer información de películas para realizar un análisis de mercado inicial.

### 1. Registro y Documentación
Tendrás que [registrarte en TMDB](https://www.themoviedb.org/signup) para obtener tu **API Key (v3 auth)** y consultar la [documentación oficial](https://developer.themoviedb.org/reference/intro/getting-started).

### 2. Objetivo del Ejercicio
Queremos que consultes la API para que te devuelva la información de las películas que empiecen por la **inicial de tu nombre** (parámetro `query`). 

Debes guardar la información en un archivo `.csv` con la siguiente estructura de columnas:

| Columna | Descripción |
| :--- | :--- |
| **id** | ID interno de la película en TMDB |
| **title** | Título de la película |
| **release_date** | Fecha de estreno |
| **genres** | Nombres de los géneros (ej: "Acción, Comedia") |
| **vote_average** | Puntuación media de los usuarios |
| **overview** | Sinopsis o resumen de la trama |

### 3. El Reto: Mapeo de Géneros
A diferencia de otras APIs, el endpoint de búsqueda de películas devuelve los géneros como una lista de IDs numéricos (ej: `[28, 12]`). 

**Tu labor es:**
1. Consultar el endpoint de "Genre List" para obtener la relación entre IDs y nombres.
2. Sustituir los IDs en tu DataFrame final por los nombres reales de los géneros (separados por comas).

---

### Código de inicio
Aquí tienes el bloque para empezar a configurar tus llamadas:

```python
import requests
import pandas as pd

# Rellena estas variables
api_key = "TU_API_KEY_AQUÍ"
url_base = "[https://api.themoviedb.org/3](https://api.themoviedb.org/3)"
mi_inicial = "P" # Sustituye por tu inicial

In [1]:
import requests
import pandas as pd

# Configuración
token = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2E5MmE2MjAzMWJiNjMxN2JlZDIyZTY5ZjU4ZjRiZSIsIm5iZiI6MTc3NDMwMDYwOC4wNjgsInN1YiI6IjY5YzFhZGMwNmMzMmM0Yzk1ZTE1ZjNhZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.cclSpjGyCC3xYOJwH0GtlX3NI7odAjGPBgsQPdJyU9g"
url_base = "https://api.themoviedb.org/3"
mi_inicial = "U" # Cambiar por la inicial del alumno

# 1. Obtener el diccionario de géneros (ID -> Nombre)
# Tip: Endpoint /genre/movie/list
def get_genres_map(token):
    path = "/genre/movie/list"
    return requests.get(url_base + path, headers = {"Authorization": f"Bearer {token}"}).json()

# 2. Buscar películas
# Tip: Endpoint /search/movie
def search_movies(token, query):
    path = "/search/movie"
    params = f"?query={query}"
    return requests.get(url_base + path + params, headers = {"Authorization": f"Bearer {token}"}).json()

# 3. Procesamiento y Limpieza
# - Mapear los IDs de géneros a nombres reales.
# - Crear el DataFrame.
# - Exportar a CSV.

In [2]:
genres = get_genres_map(token)["genres"]
genres

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [3]:
movies = search_movies(token, mi_inicial)["results"]
movies_U = [movie for movie in movies if movie["title"].lower().startswith("u")]
movies_U

[{'adult': False,
  'backdrop_path': '/zbrSxpgeNscm06Wz39qa9YP5h9m.jpg',
  'genre_ids': [16, 14],
  'id': 39405,
  'original_language': 'fr',
  'original_title': 'U',
  'overview': "Since her parents passed away, Princess Mona lives by herself in a castle with two hideous, ghastly characters, Goomi and His Lordship. One day her sobs draw the attention of a unicorn, called U, who wants to comfort and protect Mona for as long as she needs. U becomes Mona's companion, her confidant and her inseparable friend. While Mona grows into a beautiful princess, a group of charming, peaceful and fanciful Yeah-Yeah’s settles in the neighboring forest. They have no particular special powers, yet they soon bring about major changes in everyone's lives, especially in Kulka, the dreamy musician.",
  'popularity': 1.5228,
  'poster_path': '/fPyDf7cl4NrtjSn5jnmODDF70kS.jpg',
  'release_date': '2006-10-11',
  'title': 'U',
  'video': False,
  'vote_average': 6.6,
  'vote_count': 100},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [878],
  'id': 1303795,
  'original_language': 'pt',
  'original_title': 'U',
  'overview': 'The storms we go through help us deconstruct to rebuild.',
  'popularity': 0.383,
  'poster_path': '/y1BtC2GGvn09BeDrhQDGRCkHf8b.jpg',
  'release_date': '2024-05-24',
  'title': 'U',
  'video': False,
  'vote_average': 7.0,
  'vote_count': 2},
 {'adult': False,
  'backdrop_path': '/lFUOhbpG6QESi41m2oNXNKiUnTG.jpg',
  'genre_ids': [10402],
  'id': 1655272,
  'original_language': 'en',
  'original_title': 'U',
  'overview': "U is a album video that accompanies the American musician underscore's third album of the same name.",
  'popularity': 0.0952,
  'poster_path': '/a5kNdHGrqyjT8uEG641LDoDGT8b.jpg',
  'release_date': '2026-03-20',
  'title': 'U',
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/aykVIMNgq7kJSegkFXVpiDKlKaw.jpg',
  'genre_ids': [80, 18],
  'id': 1510235,
  'original_language': 'hi',
  'original_title': 'Udaipur Files: Kanhaiya Lal Tailor Murder',
  'overview': 'In June 2022, Kanhaiya Lal Sahu, a tailor in Udaipur, India, was brutally murdered. The events surrounding the murder are explored, delving into the conspiracy and the deeper issues of religious extremism, digital radicalization, and intelligence failures that led to the tragic event.',
  'popularity': 0.4261,
  'poster_path': '/dofvavrizF7KnF6Jl6g6yMp7y1B.jpg',
  'release_date': '2025-08-08',
  'title': 'Udaipur Files: Kanhaiya Lal Tailor Murder',
  'video': False,
  'vote_average': 7.0,
  'vote_count': 1},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [],
  'id': 1132364,
  'original_language': 'en',
  'original_title': 'U',
  'overview': 'A short movie by yuri A containing multiple poop facts.',
  'popularity': 0.0737,
  'poster_path': None,
  'release_date': '2002-12-30',
  'title': 'U',
  'video': False,
  'vote_average': 8.4,
  'vote_count': 7},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [],
  'id': 1373799,
  'original_language': 'el',
  'original_title': 'u',
  'overview': '',
  'popularity': 0.0362,
  'poster_path': '/dITefJWCuYhahuJeKBFgijiVERA.jpg',
  'release_date': '',
  'title': 'u',
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/cOwiPEr9cXPojo1VcwrwXHgPfGd.jpg',
  'genre_ids': [12, 14],
  'id': 43194,
  'original_language': 'it',
  'original_title': 'Ulisse',
  'overview': "A movie adaptation of Homer's second epic, that talks about Ulysses' efforts to return to his home after the end of ten years of war.",
  'popularity': 2.588,
  'poster_path': '/1HwrZ6SVRcUiPWSx3ecc7DFqey0.jpg',
  'release_date': '1954-10-06',
  'title': 'Ulysses',
  'video': False,
  'vote_average': 6.5,
  'vote_count': 208},
 {'adult': False,
  'backdrop_path': '/2EfIedXlPBE5dOAW6ciDqHxeoci.jpg',
  'genre_ids': [18, 27],
  'id': 146800,
  'original_language': 'ja',
  'original_title': '馬と女と犬',
  'overview': 'Three social outcasts who live near the seaside interact with each other in increasingly disturbing ways. The trio of characters are a woman who has killed her sister, a man who enjoys necrophilia, and a female amnesiac. The first woman engages in sadistic pursuits such as capturing young women at the beach to force them to engage in sexual activities, including copulation with a horse and a dog.',
  'popularity': 8.6442,
  'poster_path': '/iXr8TWbTQst5hwaZIbIykghIdiC.jpg',
  'release_date': '1990-05-01',
  'title': 'Uma to onna to inu',
  'video': False,
  'vote_average': 5.4,
  'vote_count': 13},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [],
  'id': 991034,
  'original_language': 'en',
  'original_title': 'U.',
  'overview': 'A girl remembers her past relationship.',
  'popularity': 0.198,
  'poster_path': '/uHS0gQiIRAhSXuRmoI9Ok8rU44G.jpg',
  'release_date': '2022-07-17',
  'title': 'U.',
  'video': False,
  'vote_average': 6.2,
  'vote_count': 4},
 {'adult': False,
  'backdrop_path': '/nrWn0blVlcdsbSrYPgCyQpTE5hn.jpg',
  'genre_ids': [80, 18, 28],
  'id': 1273948,
  'original_language': 'zh',
  'original_title': '以父亲之名',
  'overview': 'A grieving Chinese father travels to America to collect his daughter and stays to catch the killer.',
  'popularity': 2.9391,
  'poster_path': '/cPs9UvZAFs6mk2LEH3KtQdoO6SL.jpg',
  'release_date': '2026-01-15',
  'title': 'Unspoken',
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0}]

In [21]:
movies_df = pd.DataFrame(movies_U)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zbrSxpgeNscm06Wz39qa9YP5h9m.jpg,"[16, 14]",39405,fr,U,"Since her parents passed away, Princess Mona l...",1.4246,/fPyDf7cl4NrtjSn5jnmODDF70kS.jpg,2006-10-11,U,False,6.6,100
1,False,/lFUOhbpG6QESi41m2oNXNKiUnTG.jpg,[10402],1655272,en,U,U is a album video that accompanies the Americ...,0.1039,/a5kNdHGrqyjT8uEG641LDoDGT8b.jpg,2026-03-20,U,False,0.0,0
2,False,NaN,[878],1303795,pt,U,The storms we go through help us deconstruct t...,0.4343,/y1BtC2GGvn09BeDrhQDGRCkHf8b.jpg,2024-05-24,U,False,7.0,2
3,False,/aykVIMNgq7kJSegkFXVpiDKlKaw.jpg,"[80, 18]",1510235,hi,Udaipur Files: Kanhaiya Lal Tailor Murder,"In June 2022, Kanhaiya Lal Sahu, a tailor in U...",0.5905,/dofvavrizF7KnF6Jl6g6yMp7y1B.jpg,2025-08-08,Udaipur Files: Kanhaiya Lal Tailor Murder,False,7.0,1
4,False,NaN,[],1132364,en,U,A short movie by yuri A containing multiple po...,0.0897,NaN,2002-12-30,U,False,8.4,7
5,False,/cOwiPEr9cXPojo1VcwrwXHgPfGd.jpg,"[12, 14]",43194,it,Ulisse,"A movie adaptation of Homer's second epic, tha...",2.6166,/1HwrZ6SVRcUiPWSx3ecc7DFqey0.jpg,1954-10-06,Ulysses,False,6.5,208
6,False,NaN,[],1373799,el,u,,0.0143,/dITefJWCuYhahuJeKBFgijiVERA.jpg,,u,False,0.0,0
7,False,/2EfIedXlPBE5dOAW6ciDqHxeoci.jpg,"[18, 27]",146800,ja,馬と女と犬,Three social outcasts who live near the seasid...,9.9026,/iXr8TWbTQst5hwaZIbIykghIdiC.jpg,1990-05-01,Uma to onna to inu,False,5.4,13
8,False,/nrWn0blVlcdsbSrYPgCyQpTE5hn.jpg,"[80, 18, 28]",1273948,zh,以父亲之名,A grieving Chinese father travels to America t...,3.1748,/cPs9UvZAFs6mk2LEH3KtQdoO6SL.jpg,2026-01-15,Unspoken,False,0.0,0
9,False,/my0Be7yOeJzSaVBh77b7cyXE97a.jpg,"[28, 80, 53]",1071640,cn,衝鋒: 火拼,"The Yau Tsim Mong area, the core commercial ar...",5.8152,/xqu6u29ToxZos0PojcgXy2hEx9b.jpg,2026-03-05,Ultimate Revenge,False,6.0,1

In [114]:
def get_genre_str(genre_ids: str, genres: list):
    genre_names = []
    if len(genre_ids) > 0:
        for i in genre_ids:
            for genre in genres:
                if  i== genre.get("id"):
                    genre_names.append(genre.get("name"))
    else:
        genre_names.append("Unknown")        
    return ",".join(genre_names)

def create_names_map():
    genre_names_map: dict = {}
    for genre_ids in movies_df["genre_ids"]:
        key = str(genre_ids).replace("[","").replace("]", "").replace(" ", "")
        genre_names_map[key] = get_genre_str(genre_ids, genres)

    return genre_names_map

In [1]:
col = "genre_names"
pos = movies_df.columns.get_loc("genre_ids") + 1
values = movies_df["genre_ids"].astype(str).str.replace(r"[\[\]\s]", "", regex=True).map(create_names_map())

movies_names = movies_df.insert(pos, col, values)

NameError: name 'movies_df' is not defined

In [116]:
movies_df

,adult,backdrop_path,genre_ids,genre_names,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zbrSxpgeNscm06Wz39qa9YP5h9m.jpg,"[16, 14]","Animation,Fantasy",39405,fr,U,"Since her parents passed away, Princess Mona l...",1.4246,/fPyDf7cl4NrtjSn5jnmODDF70kS.jpg,2006-10-11,U,False,6.6,100
1,False,/lFUOhbpG6QESi41m2oNXNKiUnTG.jpg,[10402],Music,1655272,en,U,U is a album video that accompanies the Americ...,0.1039,/a5kNdHGrqyjT8uEG641LDoDGT8b.jpg,2026-03-20,U,False,0.0,0
2,False,NaN,[878],Science Fiction,1303795,pt,U,The storms we go through help us deconstruct t...,0.4343,/y1BtC2GGvn09BeDrhQDGRCkHf8b.jpg,2024-05-24,U,False,7.0,2
3,False,/aykVIMNgq7kJSegkFXVpiDKlKaw.jpg,"[80, 18]","Crime,Drama",1510235,hi,Udaipur Files: Kanhaiya Lal Tailor Murder,"In June 2022, Kanhaiya Lal Sahu, a tailor in U...",0.5905,/dofvavrizF7KnF6Jl6g6yMp7y1B.jpg,2025-08-08,Udaipur Files: Kanhaiya Lal Tailor Murder,False,7.0,1
4,False,NaN,[],Unknown,1132364,en,U,A short movie by yuri A containing multiple po...,0.0897,NaN,2002-12-30,U,False,8.4,7
5,False,/cOwiPEr9cXPojo1VcwrwXHgPfGd.jpg,"[12, 14]","Adventure,Fantasy",43194,it,Ulisse,"A movie adaptation of Homer's second epic, tha...",2.6166,/1HwrZ6SVRcUiPWSx3ecc7DFqey0.jpg,1954-10-06,Ulysses,False,6.5,208
6,False,NaN,[],Unknown,1373799,el,u,,0.0143,/dITefJWCuYhahuJeKBFgijiVERA.jpg,,u,False,0.0,0
7,False,/2EfIedXlPBE5dOAW6ciDqHxeoci.jpg,"[18, 27]","Drama,Horror",146800,ja,馬と女と犬,Three social outcasts who live near the seasid...,9.9026,/iXr8TWbTQst5hwaZIbIykghIdiC.jpg,1990-05-01,Uma to onna to inu,False,5.4,13
8,False,/nrWn0blVlcdsbSrYPgCyQpTE5hn.jpg,"[80, 18, 28]","Crime,Drama,Action",1273948,zh,以父亲之名,A grieving Chinese father travels to America t...,3.1748,/cPs9UvZAFs6mk2LEH3KtQdoO6SL.jpg,2026-01-15,Unspoken,False,0.0,0
9,False,/my0Be7yOeJzSaVBh77b7cyXE97a.jpg,"[28, 80, 53]","Action,Crime,Thriller",1071640,cn,衝鋒: 火拼,"The Yau Tsim Mong area, the core commercial ar...",5.8152,/xqu6u29ToxZos0PojcgXy2hEx9b.jpg,2026-03-05,Ultimate Revenge,False,6.0,1

In [ ]:
movies_names.to_csv("movies_celan.csv")