# Ex2 - Filtering and Sorting Data

### Step 1. Import the necessary libraries

In [33]:
import numpy as np
import pandas as pd

#pd.set_option('display.max_columns', None)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

In [34]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv"
df = pd.read_csv(url, sep=",")
df

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,...,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,...,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,...,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,...,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,...,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,...,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,...,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,...,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,...,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,...,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,...,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,...,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,...,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,...,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,...,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,...,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,...,4,5,0,9,9,18

### Step 3. Assign it to a variable called euro12.

In [35]:
euro12 = pd.DataFrame(df)
euro12.columns = (
    df.columns
        .str.replace(r'[%().]', '', regex=True)
        .str.replace('-', '_')
        .str.strip()
        .str.replace(' ', '_')
        .str.lower()
)
euro12.columns

Index(['team', 'goals', 'shots_on_target', 'shots_off_target',
       'shooting_accuracy', 'goals_to_shots', 'total_shots_inc_blocked',
       'hit_woodwork', 'penalty_goals', 'penalties_not_scored', 'headed_goals',
       'passes', 'passes_completed', 'passing_accuracy', 'touches', 'crosses',
       'dribbles', 'corners_taken', 'tackles', 'clearances', 'interceptions',
       'clearances_off_line', 'clean_sheets', 'blocks', 'goals_conceded',
       'saves_made', 'saves_to_shots_ratio', 'fouls_won', 'fouls_conceded',
       'offsides', 'yellow_cards', 'red_cards', 'subs_on', 'subs_off',
       'players_used'],
      dtype='str')

In [88]:
euro12.index = euro12["team"]
euro12 = euro12.drop("team", axis=1)

### Step 4. Select only the Goal column.

In [36]:
euro12["goals"]

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [40]:
euro12["team"].nunique()

16

### Step 6. What is the number of columns in the dataset?

In [42]:
len(euro12.columns)

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [46]:
discipline = euro12[["team","yellow_cards","red_cards"]]
discipline

                   team  yellow_cards  red_cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [52]:
discipline.sort_values("red_cards", ascending=False)

                   team  yellow_cards  red_cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
0               Croatia             9          0
3               England             5          0
4                France             6          0
2               Denmark             4          0
1        Czech Republic             7          0
7                 Italy            16          0
5               Germany             4          0
8           Netherlands             5          0
10             Portugal            12          0
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [49]:
discipline.sort_values("yellow_cards", ascending=False)

                   team  yellow_cards  red_cards
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
6                Greece             9          1
14               Sweden             7          0
9                Poland             7          1
1        Czech Republic             7          0
12               Russia             6          0
11  Republic of Ireland             6          1
4                France             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
5               Germany             4          0
2               Denmark             4          0

### Step 9. Calculate the mean Yellow Cards given per Team

In [53]:
discipline["yellow_cards"].mean()

np.float64(7.4375)

### Step 10. Filter teams that scored more than 6 goals

In [115]:
euro12.loc[(euro12["goals"] > 6), ["goals"]]

         goals
team
Germany     10
Spain       12

### Step 11. Select the teams that start with G

In [119]:
euro12.index[euro12.index.str.startswith("G")].tolist()

['Germany', 'Greece']

### Step 12. Select the first 7 columns

In [116]:
euro12.iloc[:, :7]

,goals,shots_on_target,shots_off_target,shooting_accuracy,goals_to_shots,total_shots_inc_blocked,hit_woodwork
team,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0
Czech Republic,4,13,18,41.9%,12.9%,39,0
Denmark,4,10,10,50.0%,20.0%,27,1
England,5,11,18,50.0%,17.2%,40,0
France,3,22,24,37.9%,6.5%,65,1
Germany,10,32,32,47.8%,15.6%,80,2
Greece,5,8,18,30.7%,19.2%,32,1
Italy,6,34,45,43.0%,7.5%,110,2
Netherlands,2,12,36,25.0%,4.1%,60,2
Poland,2,15,23,39.4%,5.2%,48,0
Portugal,6,22,42,34.3%,9.3%,82,6
Republic of Ireland,1,7,12,36.8%,5.2%,28,0
Russia,5,9,31,22.5%,12.5%,59,2
Spain,12,42,33,55.9%,16.0%,100,0
Sweden,5,17,19,47.2%,13.8%,39,3
Ukraine,2,7,26,21.2%,6.0%,38,0

### Step 13. Select all columns except the last 3.

In [90]:
euro12.iloc[:, :-3]

,goals,shots_on_target,shots_off_target,shooting_accuracy,goals_to_shots,total_shots_inc_blocked,...,saves_to_shots_ratio,fouls_won,fouls_conceded,offsides,yellow_cards,red_cards
team,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,...,81.3%,41,62,2,9,0
Czech Republic,4,13,18,41.9%,12.9%,39,...,60.1%,53,73,8,7,0
Denmark,4,10,10,50.0%,20.0%,27,...,66.7%,25,38,8,4,0
England,5,11,18,50.0%,17.2%,40,...,88.1%,43,45,6,5,0
France,3,22,24,37.9%,6.5%,65,...,54.6%,36,51,5,6,0
Germany,10,32,32,47.8%,15.6%,80,...,62.6%,63,49,12,4,0
Greece,5,8,18,30.7%,19.2%,32,...,65.1%,67,48,12,9,1
Italy,6,34,45,43.0%,7.5%,110,...,74.1%,101,89,16,16,0
Netherlands,2,12,36,25.0%,4.1%,60,...,70.6%,35,30,3,5,0
Poland,2,15,23,39.4%,5.2%,48,...,66.7%,48,56,3,7,1
Portugal,6,22,42,34.3%,9.3%,82,...,71.5%,73,90,10,12,0
Republic of Ireland,1,7,12,36.8%,5.2%,28,...,65.4%,43,51,11,6,1
Russia,5,9,31,22.5%,12.5%,59,...,77.0%,34,43,4,6,0
Spain,12,42,33,55.9%,16.0%,100,...,93.8%,102,83,19,11,0
Sweden,5,17,19,47.2%,13.8%,39,...,61.6%,35,51,7,7,0
Ukraine,2,7,26,21.2%,6.0%,38,...,76.5%,48,31,4,5,0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [99]:
euro12.loc[["England", "Italy", "Russia"],["shooting_accuracy"]]

        shooting_accuracy
team
England             50.0%
Italy               43.0%
Russia              22.5%